### ISSUE TITLE
TODO Code

### ISSUE THREAD

**Issue by geronimo-iia** [geronimo-iia/async-btree#2]
- [X] module common definition (typing)
- [X] module of meta manipulation
- [X] define submodule for decorator, leaf etc
- [x] add more example in docs
- [x] ensure tests and coverage

**Comment by geronimo-iia** [comment]
work in progress, for now i focus on test unit

**Comment by geronimo-iia** [comment]
https://github.com/geronimo-iia/async-btree/pull/3
